- hosts: all
  become: yes
  vars:
    apppath: "/home/pi/app"
    appsource: "https://jukebox.dynalias.org/maven/test/example-webservive-0.0.1.jar"
    apptarget: "webservice.jar"
  roles:
    - common
    - appserver